export const helium10KeysMap = [
  { currentKey: "ProductDetails", newKey: "title" },
  { currentKey: "ASIN", newKey: "asin" },
  { currentKey: "Brand", newKey: "brand" },
  { currentKey: "Price", newKey: "price" },
  { currentKey: "Sales", newKey: "monthlySales" },
  { currentKey: "Revenue", newKey: "monthlyRevenue" },
  { currentKey: "BSR", newKey: "salesRank" },
  { currentKey: "SellerCountryRegion", newKey: "sellerCountry" },
  { currentKey: "FBAFees", newKey: "fbaFee" },
  { currentKey: "Ratings", newKey: "ratings" },
  { currentKey: "ReviewCount", newKey: "reviewCount" },
  { currentKey: "Category", newKey: "category" },
  { currentKey: "CreationDate", newKey: "launchDate" },
];
